# Generated by Django 4.0.6 on 2022-08-18 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_detailsale_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cart',
        ),
    ]
