# Generated by Django 4.0.6 on 2022-08-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='uuid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
