# Generated by Django 4.0.6 on 2022-08-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
